version: "3.8"

services:
  ghi:
    volumes:
      - ./ghi:/app
    develop:
      watch:
        - action: sync
          path: ./ghi
          target: /app
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
